### ISSUE TITLE
Migration to Google Analytics 4 before UA switch-off on 1st July 2023

### ISSUE THREAD

**Issue by chrisaligent** [oroinc/google-tag-manager#5]
**Summary**  
On 1st July 2023 Universal Analytics (UA) will be switched off and all properties must be migrated to Google Analytics 4 (GA4).
Announcement Post:
https://support.google.com/analytics/answer/11583528?hl=en&ref_topic=10094551

Many of the eCommerce events/properties seem to now be different in GA4, as per:
https://support.google.com/analytics/answer/10119380

**Example**  
For example:
![2022-04-13_16-05](https://user-images.githubusercontent.com/45612883/163114792-ce447103-82c2-492e-9ff5-40201ae1f0e0.png)
`addToCart` is now `add_to_cart`, `currencyCode` is now `currency`, and `products` are now `items` (with a slightly different schema).

The deprecated `addToCart` event is being used by this bundle:
![2022-04-13_16-00](https://user-images.githubusercontent.com/45612883/163115046-7d624b86-9f9e-4d26-8599-a588f73b54f0.png)
`src/Oro/Bundle/GoogleTagManagerBundle/EventListener/RequestProductItemEventListener.php`

**Notes**
Although there is still 14 months before this cut-off, it may be worth prioritising this migration as all UA tracking data will be removed in early 2024. Allowing OroCommerce stores to migrate to GA4 early (preferably 12+ months beforehand) will ensure that they don't lose more than 12 months of reporting. Ideally there would be a solution to allow both UA and GA4 tracking simultaneously during the transition period.

**Comment by chrisaligent** [comment]
NOTE: I have also opened an Oro Enterprise Support ticket about this as we'd like to have the migration completed in early 2023 (preferably late 2022) to ensure a seamless transition. We have already had several clients ask about migrating.

**Comment by mbessolov** [comment]
_Internal issue ID: BB-21298_

**Comment by chrisaligent** [comment]
It looks like this has been released as part of OroCommerce Application 5.0.4:
https://github.com/oroinc/orocommerce-application/releases/tag/5.0.4

Closing issue as complete :+1:
